version: "3.8"

services:

  app:
    build: .
    container_name: gamestore_app
    depends_on:
      - db
      - mongodb
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0.42
    container_name: gamestore_bdd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MonMotDePasse
      MYSQL_DATABASE: gamestore_bdd
      MYSQL_USER: gamestore
      MYSQL_PASSWORD: LeMotDePasse
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql

phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: gamestore_pma
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_ROOT_PASSWORD: MonMotDePasse
      PMA_PASSWORD: MonMotDePasse
    depends_on:
      - db
    restart: always

volumes:
  db_data: